In [1]:
#ML - Classification - Support Vector Machine - Algorithm - GridSearchCV Method - GridSearchCV is an automatic algorithm, parameter check, and creates a table, and
#Check & upload the confusion matrix Value automatically in the table.

In [2]:
#Importing the Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
#Reading the dataset
dataset=pd.read_csv("Social_Network_Ads.csv") #Dataset file name
dataset #Function call

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
#Categorical data converting into nominal data
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0         True
1    15810944   35            20000          0         True
2    15668575   26            43000          0        False
3    15603246   27            57000          0        False
4    15804002   19            76000          0         True
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1        False
396  15706071   51            23000          1         True
397  15654296   50            20000          1        False
398  15755018   36            33000          0         True
399  15594041   49            36000          1        False

[400 rows x 5 columns]

In [5]:
indep=dataset[["Age","EstimatedSalary","Gender_Male"]] #Independent - Input dataset
dep=dataset["Purchased"] #Dependent - Output dataset

In [6]:
#split into training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [7]:
#StandardScaler for better results
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform (X_train)
X_test=sc.transform(X_test)

In [8]:
#Model Creation
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
param_grid= {'kernel':['rbf','poly','sigmoid','linear'],
              'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}


grid=GridSearchCV(SVC(probability=True),param_grid, refit=True, verbose=3, cv=5, n_jobs=-1,scoring='f1_weighted')

#Fitting the model for grid search
grid.fit(X_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

GridSearchCV(cv=5, estimator=SVC(probability=True), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             scoring='f1_weighted', verbose=3)

In [9]:
#Print best parameter after tuning
#Print(grid.best_params_)
re=grid.cv_results_

#Print (re)
grid_predictions=grid.predict(X_test)

from sklearn.metrics import confusion_matrix #Confusion Matrix Identification
cm = confusion_matrix(y_test, grid_predictions)

from sklearn.metrics import classification_report #Classification Report
clf_report = classification_report(y_test, grid_predictions)

In [10]:
from sklearn.metrics import f1_score
f1_macro=f1_score (y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}: 0.9100355779243318

In [11]:
print("The Confusion Matrix:\n",cm)

The Confusion Matrix:
 [[80  5]
 [ 7 42]]

In [12]:
print("The Confusion Matrix:\n",clf_report)

The Confusion Matrix:
               precision    recall  f1-score   support

           0       0.92      0.94      0.93        85
           1       0.89      0.86      0.88        49

    accuracy                           0.91       134
   macro avg       0.91      0.90      0.90       134
weighted avg       0.91      0.91      0.91       134

In [13]:
from sklearn.metrics import roc_auc_score #ROC -Receiver Operating Characteristic, AUC - Area Under the Curve
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9539015606242497

In [14]:
#Table Creation
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.022327,0.007336,0.007822,0.001948,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.867478,0.886792,0.869709,0.944161,0.943041,0.902236,0.034431,3
1,0.015646,0.000941,0.005543,0.000274,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.799620,0.808392,0.787943,0.924528,0.901744,0.844445,0.056918,11
2,0.010853,0.000463,0.005379,0.000319,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.762677,0.738916,0.655795,0.796284,0.766556,0.744045,0.047743,39
3,0.017389,0.000847,0.005221,0.000514,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
4,0.013163,0.000718,0.006220,0.000414,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.867478,0.886792,0.869709,0.944161,0.943041,0.902236,0.034431,3
5,0.015580,0.001734,0.005557,0.000712,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.799620,0.808392,0.787943,0.924528,0.901744,0.844445,0.056918,11
6,0.010417,0.000889,0.006010,0.000910,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.762677,0.738916,0.753180,0.778067,0.766556,0.759879,0.013172,31
7,0.016666,0.001016,0.004888,0.000134,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
8,0.017130,0.001913,0.005182,0.000224,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.867478,0.886792,0.870362,0.944161,0.943041,0.902367,0.034308,1
9,0.065979,0.007377,0.004766,0.000160,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.822092,0.787284,0.766556,0.924528,0.901744,0.840441,0.062370,13
10,0.010683,0.001067,0.004645,0.000128,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.808927,0.714931,0.633719,0.718497,0.766556,0.728526,0.058625,40
11,0.071833,0.034401,0.005367,0.001002,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
12,0.017499,0.001109,0.007854,0.003259,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.867478,0.886792,0.870362,0.944161,0.943041,0.902367,0.034308,1
13,0.064795,0.021573,0.005282,0.000403,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.822092,0.787284,0.766556,0.924528,0.901744,0.840441,0.062370,13
14,0.010435,0.001217,0.005273,0.000566,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.808927,0.714931,0.698113,0.796284,0.766556,0.756962,0.043745,32
15,0.050035,0.004094,0.004976,0.000197,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
16,0.044537,0.006224,0.005275,0.000300,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.826263,0.866968,0.851527,0.925272,0.923510,0.878708,0.039503,6
17,0.454523,0.144941,0.004859,0.000302,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
18,0.009746,0.000179,0.004735,0.000136,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.791752,0.714931,0.698113,0.796284,0.766556,0.753527,0.040048,36
19,0.297123,0.014917,0.004937,0.000253,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
20,0.041451,0.004259,0.005314,0.000263,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.847141,0.866968,0.851527,0.925272,0.923510,0.882884,0.034529,5
21,0.543979,0.175134,0.005001,0.000198,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
22,0.009979,0.000510,0.004905,0.000272,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.808927,0.714931,0.698113,0.796284,0.766556,0.756962,0.043745,32
23,0.322545,0.052944,0.005002,0.000538,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
24,0.078467,0.012495,0.005619,0.000630,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.826263,0.866968,0.851527,0.886792,0.903610,0.867032,0.026948,7
25,0.998659,0.194777,0.005298,0.000535,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
26,0.010372,0.000659,0.004623,0.000115,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.791752,0.714931,0.698113,0.796284,0.766556,0.753527,0.040048,36
27,0.695485,0.130211,0.004832,0.000179,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
28,0.085498,0.010944,0.005271,0.000305,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.826263,0.866968,0.851527,0.886792,0.903610,0.867032,0.026948,7
29,0.998802,0.274951,0.004970,0.000333,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
30,0.009984,0.000411,0.004596,0.000213,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",0.808927,0.714931,0.698113,0.796284,0.766556,0.756962,0.043745,32
31,0.759355,0.288517,0.004753,0.000223,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
32,0.100130,0.015239,0.005827,0.001503,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.826263,0.866968,0.851527,0.847020,0.883278,0.855011,0.019206,9
33,1.505011,0.406854,0.004814,0.000291,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
34,0.009845,0.000600,0.004716,0.000274,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.791752,0.714931,0.698113,0.796284,0.766556,0.753527,0.040048,36
35,1.003959,0.151946,0.005027,0.000369,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21
36,0.098493,0.026819,0.007731,0.004884,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.826263,0.866968,0.851527,0.847020,0.883278,0.855011,0.019206,9
37,1.653369,0.617729,0.004859,0.000173,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.822092,0.765553,0.766556,0.924528,0.901744,0.836095,0.066541,15
38,0.010034,0.000579,0.005058,0.000467,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",0.808927,0.714931,0.698113,0.796284,0.766556,0.756962,0.043745,32
39,0.807454,0.073235,0.004532,0.000503,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.776290,0.790949,0.698235,0.923510,0.901744,0.818146,0.083619,21

In [15]:
#Input
age_input=float(input("Age:"))
salary_input=float(input("salary:"))
sex_male_input=int(input("Sex Male 0 or 1:"))

Age: 26
salary: 43000
Sex Male 0 or 1: 0

In [16]:
#Future Prediction

future_prediction=grid.predict([[age_input,salary_input,sex_male_input]])
print("Future_prediction={}".format(future_prediction))

Future_prediction=[1]