In [1]:
#ML - Classification - Decision Tree - Algorithm - GridSearchCV Method - GridSearchCV is an automatic algorithm, parameter check, and creates a table, and
#Check & upload the confusion matrix Value automatically in the table.

In [2]:
#Importing the Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
#Reading the dataset
dataset=pd.read_csv("Social_Network_Ads.csv") #Dataset file name
dataset #Function call

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
#Categorical data converting into nominal data
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0         True
1    15810944   35            20000          0         True
2    15668575   26            43000          0        False
3    15603246   27            57000          0        False
4    15804002   19            76000          0         True
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1        False
396  15706071   51            23000          1         True
397  15654296   50            20000          1        False
398  15755018   36            33000          0         True
399  15594041   49            36000          1        False

[400 rows x 5 columns]

In [5]:
indep=dataset[["Age","EstimatedSalary","Gender_Male"]] #Independent - Input dataset
dep=dataset["Purchased"] #Dependent - Output dataset

In [6]:
#split into training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [7]:
#StandardScaler for better results
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform (X_train)
X_test=sc.transform(X_test)

In [10]:
#Model Creation
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
param_grid= {'criterion':['gini','entropy'],
              'max_features':['sqrt','log2'],'splitter':['best','random']}


grid=GridSearchCV(DecisionTreeClassifier(),param_grid, refit=True, verbose=3, n_jobs=-1,scoring='f1_weighted')

#Fitting the model for grid search
grid.fit(X_train,y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [11]:
#Print best parameter after tuning
#Print(grid.best_params_)
re=grid.cv_results_

#Print (re)
grid_predictions=grid.predict(X_test)

from sklearn.metrics import confusion_matrix #Confusion Matrix Identification
cm = confusion_matrix(y_test, grid_predictions)

from sklearn.metrics import classification_report #Classification Report
clf_report = classification_report(y_test, grid_predictions)

In [12]:
from sklearn.metrics import f1_score
f1_macro=f1_score (y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'sqrt', 'splitter': 'best'}: 0.8546043244326981

In [13]:
print("The Confusion Matrix:\n",cm)

The Confusion Matrix:
 [[80  5]
 [14 35]]

In [14]:
print("The Confusion Matrix:\n",clf_report)

The Confusion Matrix:
               precision    recall  f1-score   support

           0       0.85      0.94      0.89        85
           1       0.88      0.71      0.79        49

    accuracy                           0.86       134
   macro avg       0.86      0.83      0.84       134
weighted avg       0.86      0.86      0.85       134

In [15]:
from sklearn.metrics import roc_auc_score #ROC -Receiver Operating Characteristic, AUC - Area Under the Curve
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.8277310924369748

In [16]:
#Table Creation
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.035337,0.018596,0.018332,0.008340,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.867478,0.889022,0.832483,0.886792,0.844370,0.864029,0.022523,1
1,0.002508,0.000702,0.005483,0.000384,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.843811,0.888107,0.778179,0.808775,0.924528,0.848680,0.052714,2
2,0.002162,0.000220,0.006256,0.001723,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.759544,0.888107,0.815056,0.869709,0.883278,0.843139,0.049226,3
3,0.002209,0.000392,0.005520,0.000976,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.799620,0.886792,0.796284,0.868632,0.829124,0.836091,0.036312,6
4,0.002800,0.000907,0.005529,0.000670,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.804764,0.811321,0.795256,0.886792,0.883278,0.836282,0.040148,5
5,0.002147,0.000189,0.005090,0.000126,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.829615,0.850809,0.793565,0.813179,0.775815,0.812597,0.026326,8
6,0.002227,0.000280,0.005598,0.000825,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.782557,0.850809,0.851527,0.870362,0.844370,0.839925,0.029968,4
7,0.002257,0.000203,0.004888,0.000575,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.847141,0.828959,0.756031,0.868632,0.847020,0.829557,0.038852,7

In [17]:
#Input
age_input=float(input("Age:"))
salary_input=float(input("salary:"))
sex_male_input=int(input("Sex Male 0 or 1:"))

Age: 36
salary: 33000
Sex Male 0 or 1: 1

In [18]:
#Future Prediction

future_prediction=grid.predict([[age_input,salary_input,sex_male_input]])
print("Future_prediction={}".format(future_prediction))

Future_prediction=[1]